<!DOCTYPE html>

<?php include "navbar.php" ?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
    .container
    {       
       height: 500px;
    }
    .heading
    {
       width: 400px;
      text-align: center;
     margin-left: 400px;
    }
    .expertimg
    {
        margin-top:30px;
        margin-left: 20px;
        display: flex;
    }
    .About p
    {
        display: flex;
        width: 800px;
        margin-left: 500px;
        margin-top: -295px
    }
    .expertbutton
    {
        margin-top:10px;
        border-style:solid;
        margin-left: 500px;
        width: 100px;
        height: 50px;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        font-size: 15px;
        cursor: pointer;
    }

   </style>
    
</head>
<body>
    <div class="container">
        <h1 class="heading">Expert exchange </h1>
        <img class="expertimg" src="expert image.png">
        <div class="About"> 
            <p>
                Expert exchange is a platform where industry and academia are mutually benefitted by sharing their expertise. Eminent personalities from reputed organizations are invited to share their knowledge and experience with budding minds. Their rich experience and wealth of knowledge provide abundant insights to the professionals of tomorrow.

For the Expert Exchange Orena Solutions must be briefed on the desired objective and outcome of the lecture, the experience level in years of the expert required, targeted audience, time and location. After analyzing the expert details and background, the details shall be shared with the concerned person from the company.

            </p>
        </div>
        <button class="expertbutton">learn more</button>
        
    </div>
    
</body>
</html>

</body>

<?php include "footer.php" ?>
</html>